server:
  shutdown: graceful
spring:
  web:
    graceful
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/rafia
      username:
      password:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    password: guest
    port: 61613
    host: localhost
    username: guest

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    dev.yangsijun.rafia.*: TRACE
