server:
  shutdown: graceful
  port: 80
spring:
  web:
    graceful
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/rafia
      username:
      password:
    redis:
      host: 127.0.0.1
      port: 6379
  rabbitmq:
    password: guest
    port: 61613
    host: 127.0.0.1
    username: guest

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
    dev.yangsijun.rafia.*: TRACE
